version: '3.8'

services:
  db:
    image: postgres:14.5
    container_name: postgres_django
    volumes:
      - ./data_postgres/db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB : ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  pgadmin:
      image: dpage/pgadmin4:6.18
      container_name: pgadmin4
      restart: always
      environment:
          PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
          PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      ports:
          - "5050:80"
  django_gunicorn:
    container_name: django_gunicorn
    restart: always
    env_file:
      - .env
    volumes:
      - static:/static
    build: .
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static: