# Generated by Django 3.2.18 on 2023-03-07 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='External_service',
            fields=[
                ('Asset_Code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Service_Detail', models.CharField(max_length=100)),
                ('Vendor_Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Product', models.CharField(max_length=100)),
                ('Confidential', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('Integrity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('Availability', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('Service_Owner', models.CharField(max_length=100)),
                ('Contract_Number', models.CharField(max_length=100)),
                ('Contract_Start_Date', models.DateField()),
                ('Contract_End_Date', models.DateField()),
                ('Repository', models.CharField(max_length=100)),
                ('Storage_Media', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'External_service',
            },
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('Asset_Code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Asset_Number', models.CharField(max_length=100)),
                ('Asset_Type', models.CharField(max_length=100)),
                ('Service', models.CharField(max_length=100)),
                ('Asset_Name', models.CharField(max_length=100)),
                ('System_Type', models.CharField(max_length=100)),
                ('Confidential', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('Integrity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('Availability', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('Owner', models.CharField(max_length=100)),
                ('User', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('MA_Start', models.DateField()),
                ('MA_End', models.DateField()),
                ('Brand_Model', models.CharField(max_length=100)),
                ('Serial_Number', models.CharField(max_length=100)),
                ('Remark', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Asset_Status', models.CharField(max_length=100)),
                ('Hardware_Type', models.CharField(max_length=100)),
                ('Software_Version', models.CharField(max_length=100)),
                ('Software_License', models.CharField(max_length=100)),
                ('Latest_Change', models.CharField(max_length=100)),
                ('Current_Software_Version', models.CharField(max_length=100)),
                ('Related_CI', models.CharField(max_length=100)),
                ('Processor_Type', models.CharField(max_length=100)),
                ('Processor_Speed', models.CharField(max_length=100)),
                ('Memory_Size', models.CharField(max_length=100)),
                ('Disk_Size', models.CharField(max_length=100)),
                ('IP_Address', models.GenericIPAddressField()),
                ('MAC_Address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Hardware',
            },
        ),
        migrations.CreateModel(
            name='In_house_service',
            fields=[
                ('Asset_Code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Service_Detail', models.CharField(max_length=100)),
                ('Asset_Type', models.CharField(max_length=100)),
                ('Confidential', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('Integrity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('Availability', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('Responsible_Person', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'In_house_service',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('Asset_Code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Asset_Type', models.CharField(max_length=100)),
                ('System_Name', models.CharField(max_length=100)),
                ('Asset_Name', models.CharField(max_length=100)),
                ('Confidential', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('Integrity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('Availability', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('Owner', models.CharField(max_length=100)),
                ('Info_Repository', models.CharField(max_length=100)),
                ('Asset_Number', models.CharField(max_length=100)),
                ('Storage_Media', models.CharField(max_length=100)),
                ('Storage_Period', models.CharField(max_length=100)),
                ('Responsible_Person', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Information',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('Employee_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Employee_Name', models.CharField(max_length=100)),
                ('Section', models.CharField(max_length=100)),
                ('Position', models.CharField(max_length=100)),
                ('Responsibilities', models.CharField(choices=[('หัวหน้าแผนก', 'หัวหน้าแผนก'), ('เจ้าหน้าที่รับผิดชอบระบบงาน', 'เจ้าหน้าที่รับผิดชอบระบบงาน')], max_length=100)),
                ('Confidential', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('Integrity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('Availability', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('Contact_Number', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'People',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('Asset_Code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Asset_Name', models.CharField(max_length=100)),
                ('Software_Vendor', models.CharField(max_length=100)),
                ('License_Unit', models.IntegerField()),
                ('Asset_Type', models.CharField(max_length=100)),
                ('System_Type', models.CharField(max_length=100)),
                ('Confidential', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('Integrity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('Availability', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('Owner', models.CharField(max_length=100)),
                ('Software_Repository', models.CharField(max_length=100)),
                ('Registered_Date', models.DateField()),
                ('Asset_Number', models.CharField(max_length=100)),
                ('Software_Status', models.CharField(choices=[('Available', 'Available'), ('UnAvailable', 'UnAvailable')], max_length=100)),
                ('Software_Version', models.CharField(max_length=100)),
                ('License_Info', models.CharField(max_length=100)),
                ('Latest_Change', models.CharField(max_length=100)),
                ('Latest_Software_Version', models.CharField(max_length=100)),
                ('Related_CI', models.CharField(max_length=100)),
                ('Vendor_Contact', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Software',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Database', models.CharField(max_length=100, verbose_name="person's first name")),
                ('Record', models.CharField(max_length=100)),
                ('ACTION', models.CharField(max_length=100)),
                ('DATE_TIME', models.DateTimeField(auto_now_add=True)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'History',
            },
        ),
    ]
